### ISSUE TITLE
how to set it up

### ISSUE THREAD

**Issue by ghost** [benkaiser/pages-pastebin#1]
I don't understand how you can do the same but with your own repository

**Comment by benkaiser** [comment]
@dentlis see blog post here:
https://benkaiser.dev/writable-websites-using-github-pages-github-action/

**Comment by ghost** [comment]
"create a GitHub Action" this https://docs.github.com/en/actions/quickstart ?

**Comment by ghost** [comment]
I just need more precise instructions 😅

**Comment by benkaiser** [comment]
The action is simply a file in a specific location in the repo, you can see it in this repo here:

https://github.com/benkaiser/pages-pastebin/blob/master/.github/workflows/upload.yml

**Comment by ghost** [comment]
> The action is simply a file in a specific location in the repo, you can see it in this repo here:
> 
> https://github.com/benkaiser/pages-pastebin/blob/master/.github/workflows/upload.yml

I did it and now I need to paste Your code?

**Comment by benkaiser** [comment]
Well, if you want it to be exactly the same, you can just fork this repo. What are you trying to achieve?

**Comment by ghost** [comment]
i forked Your repository when i go to https://dentlis.github.io/pages-pastebin/ and want to save paste it takes forever to load, how can i solve this problem? what did i do wrong? I don't understand...

**Comment by benkaiser** [comment]
@dentlis did you install the github app to your repo like I outlined in the blog post?
> Install the [GitHub app to your repo](https://github.com/apps/public-action-trigger) to allow [repository_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) to be called unauthenticated.

**Comment by ghost** [comment]
yes, https://imgur.com/jhq3BY2.png

**Comment by ghost** [comment]
I understand that I need to replace here with my repository and owner...? https://imgur.com/URkqm43.png

**Comment by ghost** [comment]
> I understand that I need to replace here with my repository and owner...? https://imgur.com/URkqm43.png

i replaced it with fetch("https://publicactiontrigger.azurewebsites.net/api/dispatches/dentlis/pages-pastebin", it turns out before that it saved everything paste to your repo

**Comment by ghost** [comment]
logically, it should be stored in my repo, but the download is still endless, what else should I do to make everything work?

**Comment by ghost** [comment]
Your repository has user-user action authors, did you add it yourself? Or did it automatically add itself?

**Comment by benkaiser** [comment]
@dentlis the fetch request that is happening when creating a paste, is it failing? What is the error?

**Comment by ghost** [comment]
thanks bro, it worked for me, thanks for the time spent on me

**Comment by ghost** [comment]
> > I understand that I need to replace here with my repository and owner...? https://imgur.com/URkqm43.png
> 
> i replaced it with fetch("https://publicactiontrigger.azurewebsites.net/api/dispatches/dentlis/pages-pastebin", it turns out before that it saved everything paste to your repo

I waited a little more, and everything worked for me!

**Comment by benkaiser** [comment]
Fantastic, great to hear @dentlis !

**Comment by ghost** [comment]
hahaha, I m nub to this :D (git, github, etc.)
